version: '3'
services:
   dashboard:
      # Not using the prebuild container as it is out of date
      # See: https://github.com/bee-queue/arena/issues/93
      build: ./services/dashboard
      ports:
         - '3001:4567'
   producer:
      build: ./services/producer
      ports:
         - '3000:3000'
   worker:
      build: ./services/worker
   redis:
      image: 'redis:alpine'
